---
on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  publish:
    runs-on: codeberg-small
    container:
      image: ghcr.io/astral-sh/uv:trixie
    steps:
      - uses: actions/checkout@v6

      - name: Build
        run: |
          uv run .github/scripts/build.py

      - uses: actions/git-pages@v2
        with:
          site: https://adafede.codeberg.page/marimo
          token: ${{ forge.token }}
          source: _site/
